=== panasenkosa/oranj/src/main/resources/oranj-mappings-1.0.dtd
<!ELEMENT mappings ((class-mapping | value-mapping | oracle-package)*)>

        <!ELEMENT class-mapping (oracle-type*, field*, property-group*)>
        <!ATTLIST class-mapping class CDATA #REQUIRED>
        <!ATTLIST class-mapping oracle-type CDATA #REQUIRED>
        <!ATTLIST class-mapping owner CDATA #IMPLIED>
        <!ATTLIST class-mapping field-mapping (exact|custom) "custom">
        <!ATTLIST class-mapping include-fields CDATA #IMPLIED>
        <!ATTLIST class-mapping exclude-fields CDATA #IMPLIED>


        <!ELEMENT field EMPTY>
        <!ATTLIST field name    CDATA #REQUIRED>
        <!ATTLIST field oracle-name CDATA #IMPLIED>
        <!ATTLIST field element-class CDATA #IMPLIED>
        <!ATTLIST field collection-merging (update|reload|append) "reload">

        <!ELEMENT property-group (property*)>
        <!ATTLIST property-group name    CDATA #IMPLIED>
        <!ATTLIST property-group behaviour    (skip|pass) "pass">
        <!ATTLIST property-group default    (true|false) "false">

        <!ELEMENT property EMPTY>
        <!ATTLIST property name  CDATA #REQUIRED>
        <!ATTLIST property property-group  CDATA #IMPLIED>

        <!ELEMENT value-mapping (sql-type*)>
        <!ATTLIST value-mapping class CDATA #REQUIRED>

        <!ELEMENT sql-type EMPTY>
        <!ATTLIST sql-type name CDATA #REQUIRED>
        <!ATTLIST sql-type to-oracle-method CDATA #IMPLIED>
        <!ATTLIST sql-type from-oracle-method CDATA #IMPLIED>
        <!ATTLIST sql-type bind-method CDATA #IMPLIED>
        <!ATTLIST sql-type update-method CDATA #IMPLIED>


        <!ELEMENT oracle-type (procedure*)>
        <!ATTLIST oracle-type class CDATA #REQUIRED>

        <!ELEMENT oracle-package (procedure*)>
        <!ATTLIST oracle-package class CDATA #REQUIRED>
        <!ATTLIST oracle-package name CDATA #REQUIRED>
        <!ATTLIST oracle-package owner CDATA #IMPLIED>

        <!ELEMENT procedure (return?, argument*)>
        <!ATTLIST procedure java-name CDATA #REQUIRED>
        <!ATTLIST procedure oracle-name CDATA #REQUIRED>
        <!ATTLIST procedure in-group CDATA #IMPLIED>
        <!ATTLIST procedure out-group CDATA #IMPLIED>

        <!ELEMENT argument EMPTY>
        <!ATTLIST argument position CDATA #REQUIRED>
        <!ATTLIST argument class    CDATA #REQUIRED>
        <!ATTLIST argument oracle-name CDATA #IMPLIED>
        <!ATTLIST argument element-class CDATA #IMPLIED>
        <!ATTLIST argument in-group CDATA #IMPLIED>
        <!ATTLIST argument out-group CDATA #IMPLIED>
        <!ATTLIST argument collection-merging (update|reload|append) "reload">

        <!ELEMENT return EMPTY>
        <!ATTLIST return class    CDATA #REQUIRED>
        <!ATTLIST return element-class CDATA #IMPLIED>
        <!ATTLIST return in-group CDATA #IMPLIED>
        <!ATTLIST return out-group CDATA #IMPLIED>

=== panasenkosa/oranj/src/main/resources/default-mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//oranj/oranj mappings DTD 1.0//EN"
		"oranj-mappings-1.0.dtd">

<mappings>

	<value-mapping class="java.lang.String">					
			<sql-type name="CHAR"/>
			<sql-type name="VARCHAR2"/>
			<sql-type name="CHARACTER"/>
			<sql-type name="STRING"/>
			<sql-type name="VARCHAR"/>
			<sql-type name="LONG"/>
			<sql-type name="CLOB"
			to-oracle-method="org.oranj.convert.standards.LobConversions.stringToClob"
			from-oracle-method="org.oranj.convert.standards.LobConversions.clobToString" />
			<sql-type name="ROWID"/>																	
	</value-mapping>

	<value-mapping class="java.util.Date">					
			<sql-type name="DATE"
			to-oracle-method="org.oranj.convert.standards.DateConversions.utilDateToDate"
			from-oracle-method="org.oranj.convert.standards.DateConversions.utilDateFromDate" />
			<sql-type name="TIMESTAMP"
			to-oracle-method="org.oranj.convert.standards.DateConversions.utilDateToDate"
			from-oracle-method="org.oranj.convert.standards.DateConversions.utilDateFromDate" />
	</value-mapping>

	<value-mapping class="[B">					
			<sql-type name="BLOB"
			to-oracle-method="org.oranj.convert.standards.LobConversions.byteArrayToBlob"
			from-oracle-method="org.oranj.convert.standards.LobConversions.blobToByteArray" />
	</value-mapping>	

	<value-mapping class="java.math.BigDecimal">					
		<sql-type name="PLS_INTEGER"/>
		<sql-type name="BINARY_INTEGER"/>
		<sql-type name="NATURAL"/>
		<sql-type name="NATURALN"/>
		<sql-type name="POSITIVE"/>
		<sql-type name="POSITIVEN"/>
		<sql-type name="NUMBER" />
		<sql-type name="DEC" />
		<sql-type name="DECIMAL" />
		<sql-type name="NUMERIC" />
		<sql-type name="FLOAT" />
		<sql-type name="INT"/>
		<sql-type name="SMALLINT"/>
		<sql-type name="INTEGER"/>
		<sql-type name="REAL" />																	
	</value-mapping>

	<value-mapping class="java.math.BigInteger">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.bigIntegerToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToBigInteger" />
	</value-mapping>

	<value-mapping class="byte">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToByte" />
	</value-mapping>

	<value-mapping class="java.lang.Byte">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToByte" />
	</value-mapping>	
	
	<value-mapping class="java.lang.Short">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToShort" />
	</value-mapping>
		
	<value-mapping class="short">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToShort" />
	</value-mapping>
	
	<value-mapping class="int">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToInt" />
			<sql-type name="INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.int_INTEGER"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.INTEGER_int" />
			<sql-type name="BINARY_INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.int_BINARYINTEGER"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYINTEGER_int" />
	</value-mapping>
		
	<value-mapping class="java.lang.Integer">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.intToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToInt" />
			<sql-type name="INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.int_INTEGER"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.INTEGER_int" />
			<sql-type name="BINARY_INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.int_BINARYINTEGER"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYINTEGER_int" />
	</value-mapping>	
	
	<value-mapping class="long">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
			<sql-type name="INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
			<sql-type name="LONG"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
	</value-mapping>	
	
	<value-mapping class="java.lang.Long">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
			<sql-type name="INTEGER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
			<sql-type name="LONG"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.longToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToLong" />
	</value-mapping>
	
	<value-mapping class="float">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.doubleToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToFloat" />
			<sql-type name="BINARY_FLOAT"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.float_BINARYFLOAT"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYFLOAT_float" />
	</value-mapping>	
	
	<value-mapping class="java.lang.Float">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.doubleToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToFloat" />
			<sql-type name="BINARY_FLOAT"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.float_BINARYFLOAT"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYFLOAT_float" />
	</value-mapping>	
	
	<value-mapping class="double">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.doubleToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToDouble" />
			<sql-type name="BINARY_DOUBLE"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.double_BINARYDOUBLE"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYDOUBLE_double" />
	</value-mapping>	
		
	<value-mapping class="java.lang.Double">					
			<sql-type name="NUMBER"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.doubleToBigDecimal"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToDouble" />
			<sql-type name="BINARY_DOUBLE"
				to-oracle-method="org.oranj.convert.standards.NumberConversions.double_BINARYDOUBLE"
				from-oracle-method="org.oranj.convert.standards.NumberConversions.BINARYDOUBLE_double" />
	</value-mapping>				
	
	<value-mapping class="boolean">
		<sql-type name="NUMBER"
			to-oracle-method="org.oranj.convert.standards.NumberConversions.booleanToBigDecimal"
			from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToBoolean" />
	</value-mapping>

	<value-mapping class="java.lang.Boolean">
		<sql-type name="NUMBER"
			to-oracle-method="org.oranj.convert.standards.NumberConversions.booleanToBigDecimal"
			from-oracle-method="org.oranj.convert.standards.NumberConversions.bigDecimalToBoolean" />
	</value-mapping>


</mappings>
